---
server:
  port: 8081

env: dev

site:
  title: hello-${env}
  author: ciara

allows:
  - 127.0.0.1
  - 192.168.10.11

spring:
   profiles: dev
---
server:
  port: 8082

env: test

site:
  title: hello-${env}
  author: ciara

allows:
  - 127.0.0.1
  - 192.168.10.11


spring:
  profiles: test
---

spring:
  profiles:
    active: dev